### PR TITLE
Whelen 400 mounted fix

### PR DESCRIPTION
**Pull request by jooiiee**
* Renamed component from 600 mounted to 400 mounted
* Added patterns
* Renamed metas to 400
* Renamed file from 600 to 400

Could cause legacy issues since it has been called 600 since 2016 (added in estates park), but since it has not had a pattern it should be quite risk free.

### CODE REVIEW

**Comment by JoshPiper** [comment]
Perhaps it'd be better having the component be registered twice. Once under 600, with a deprecated flag, pointing at the 400.

**Comment by jooiiee** [comment]
That sounds appropriate. But I'm not really sure how to do that, could you assist? I think you should have edit permissions since you're a maintainer of this repo.

**Comment by JoshPiper** [comment]
For sure, it's not too hard, so I'll give you the information first.
```lua
COMPONENT.Deprecated = "Use the 'Whelen Ion Split' with phase 'Interior'"
```
The message is just printed out.

So you'd end up with two files. whelen_400_mounted (or whatever the file name is), and the 600 (which has the .Deprecated) in it.

**Review by JoshPiper — APPROVED** [review]
Looks fine code-wise.

**Review by SuperMighty1 — APPROVED** [review]
Looks good.

**Pull request merged**
