### PR TITLE
D&R RDS 17 CANADA

### PR DESCRIPTION
**Pull request by ANorthCanadianFriend**
added sound files and LUA file for RDS 17 Siren.

### CODE REVIEW

**Review by JoshPiper — CHANGES_REQUESTED** [review]
The siren file is in the wrong directory. It needs to be in autorun/photon/library/sirens.

**Comment by ANorthCanadianFriend** [comment]
Revert "rds 17" Has the sound files, d&r rds 17 canada has the LUA File. Other files are trial and error.

**Comment by ANorthCanadianFriend** [comment]
I'll wait til you're awake Josh, I'll need some help tmrw on this.

**Review by JoshPiper — APPROVED** [review]

**Review by JoshPiper — CHANGES_REQUESTED** [review]
I've moved sirens into their own folders and renamed them to be easier to find.

The stinger and inter-clear both need icons set, see available icons in https://github.com/photonle/Photon/blob/development/lua/autorun/photon/cl_photon_hud.lua#L18-L29 or https://github.com/photonle/Photon/blob/development/lua/autorun/photon/cl_photon_hud.lua#L644-L646

Inter Clear and Wail both need loop points setting on them.

**Comment by JoshPiper** [comment]
Going to be redone by Gore.

**Pull request closed without merging**
