### PR TITLE
Updated Storm Pro Name

### PR DESCRIPTION
**Pull request by DatedGore**
From my research on the Storm Pro the current one isnt the Storm Pro but just the regular Storm siren.

### CODE REVIEW

**Review by JoshPiper — APPROVED** [review]

**Comment by JoshPiper** [comment]
Sorry for the delay, I hadn't subscribed to this.

I'll get input from creator, but all seems good on the technical front.

**Review by creator2013 — CHANGES_REQUESTED** [review]
Seems like it's really the storm siren and not the storm pro.
But I have one request. Change the path of the sounds (code + files) to correspond with the actual siren name.

**Comment by DatedGore** [comment]
okay will do crator

**Comment by DatedGore** [comment]
there ya go

**Review by JoshPiper — CHANGES_REQUESTED** [review]
Is the desktop.ini file needed?

**Comment by DatedGore** [comment]
I dont know, never remember it being there. So im guessing not?

**Review by creator2013 — APPROVED** [review]

**Review by JoshPiper — APPROVED** [review]

**Pull request merged**
