### PR TITLE
Redid Fed Sig 80K

### PR DESCRIPTION
**Pull request by DatedGore**
Redid Wail and Yelp. Added Priority, and Hilo

### CODE REVIEW

**Comment by DatedGore** [comment]
oh yeah i left out the airhorn in the title. I redid horn as well

**Review by JoshPiper — APPROVED** [review]
No issues with function.
Haven't checked the sounds themselves.

**Comment by DatedGore** [comment]
Okay.

**Comment by DatedGore** [comment]
um. I never pulled the street thunder but somehow it automatically went here.

**Comment by DatedGore** [comment]
I guess this has galls now too. But need to fix where it says it doesnt have the phaser and hilo from 80k

**Pull request closed without merging**
